# Generated by Django 3.2.9 on 2021-11-15 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_alter_flight_estimatetimedeparture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='flighNumber',
            new_name='flightNumber',
        ),
    ]
